name: Sync to VNG Cloud with s3cmd

on:
  push:
    branches: [main]
    paths:
      - 'vn/**'
  workflow_dispatch:

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install s3cmd
        run: |
          pip install s3cmd
      
      - name: Configure s3cmd
        run: |
          echo "[default]" > ~/.s3cfg
          echo "access_key = ${{ secrets.S3_ACCESS_KEY_ID }}" >> ~/.s3cfg
          echo "secret_key = ${{ secrets.S3_SECRET_ACCESS_KEY }}" >> ~/.s3cfg
          echo "host_base = hcm04.vstorage.vngcloud.vn" >> ~/.s3cfg
          echo "host_bucket = %(bucket)s.hcm04.vstorage.vngcloud.vn" >> ~/.s3cfg
          echo "use_https = True" >> ~/.s3cfg
          # Thêm các tùy chọn cần thiết khác
          echo "signature_v2 = False" >> ~/.s3cfg  # Nhiều S3-compatible cần v2 signature
      
      - name: Test connection
        run: |
          s3cmd ls
      
      - name: Sync to VNG Cloud
        run: |
          s3cmd sync --delete-removed ./vn/ s3://test-git-action/vn/
      
      - name: Call sync KB API
        if: ${{ success() }}
        run: |
          curl -X POST http://103.196.239.132:8000/kb/sync-kb \
            -H "Content-Type: application/json" \
