name: Sync to VNG Cloud with s3cmd

on:
  push:
    branches: [main]
    paths:
      - 'vn/**'
  workflow_dispatch:

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install s3cmd
        run: |
          pip install s3cmd
      
      - name: Create .s3cfg file
        run: |
          cat <<EOF > .s3cfg
          [default]
          access_key = ${{ secrets.VNG_ACCESS_KEY }}
          secret_key = ${{ secrets.VNG_SECRET_KEY }}
          host_base = hcm04.vstorage.vngcloud.vn
          host_bucket = %(bucket)s.hcm04.vstorage.vngcloud.vn
          use_https = True
          EOF

      - name: List bucket
        run: s3cmd --config=.s3cfg ls

      - name: Sync to VNG Cloud
        run: |
          s3cmd --config=~/.s3cfg sync --delete-removed ./vn/ s3://test-git-action/vn/
      
      - name: Call sync KB API
        if: ${{ success() }}
        run: |
          curl -X POST http://103.196.239.132:8000/kb/sync-kb \
            -H "Content-Type: application/json" \
