name: Sync to VNG Cloud with s3cmd

on:
  push:
    branches: [main]
    paths:
      - 'vn/**'
  workflow_dispatch:

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install s3cmd
        run: |
          pip install s3cmd
      
      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg << EOL
          [default]
          access_key = ${{ secrets.S3_ACCESS_KEY_ID }}
          secret_key = ${{ secrets.S3_SECRET_ACCESS_KEY }}
          host_base = hcm04.vstorage.vngcloud.vn
          host_bucket = %(bucket)s.hcm04.vstorage.vngcloud.vn
          use_https = True
          signature_v2 = False
          EOL
          
          # Kiểm tra file cấu hình
          ls -la ~/ | grep .s3cfg
          cat ~/.s3cfg | grep -v secret_key
      
      - name: Test connection
        run: |
          s3cmd --config=~/.s3cfg ls
      
      - name: Sync to VNG Cloud
        run: |
          s3cmd --config=~/.s3cfg sync --delete-removed ./vn/ s3://test-git-action/vn/
      
      - name: Call sync KB API
        if: ${{ success() }}
        run: |
          curl -X POST http://103.196.239.132:8000/kb/sync-kb \
            -H "Content-Type: application/json" \
